In [2]:
%pip install keras tensorflow tensorflow-keras numpy pandas scikit-learn matplotlib

Note: you may need to restart the kernel to use updated packages.


In [4]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense, LSTM
 
# 1. 데이터
x = array([[1,2,3], [2,3,4], [3,4,5], [4,5,6]])
y = array([4,5,6,7])
 
print('x shape : ', x.shape) # (4,3)
print('y shape : ', y.shape) # (4,)
#  x  y
# 123 4
# 234 5
# 345 6
# 456 7
 
print(x)
print('-------x reshape-----------')
x = x.reshape((x.shape[0], x.shape[1], 1)) # (4,3,1) reshape 전체 곱 수 같아야 4*3=4*3*1
print('x shape : ', x.shape)
print(x)
#  x        y
# [1][2][3] 4
# .....
 
# 2. 모델 구성
model = Sequential()
model.add(LSTM(10, activation = 'relu', input_shape=(3,1)))
# DENSE와 사용법 동일하나 input_shape=(열, 몇개씩잘라작업)
model.add(Dense(5))
model.add(Dense(1))
 
model.summary()
 
# 3. 실행
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=100, batch_size=1)
 
x_input = array([6,7,8])
x_input = x_input.reshape((1,3,1))
 
yhat = model.predict(x_input)
print(yhat)


I0000 00:00:1775882321.825848  622149 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1775882321.827302  622149 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1775882321.892573  622149 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI AVX_VNNI_INT8 AVX_NE_CONVERT FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1775882323.456693  622149 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENAB

x shape :  (4, 3)
y shape :  (4,)
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
-------x reshape-----------
x shape :  (4, 3, 1)
[[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]

 [[3]
  [4]
  [5]]

 [[4]
  [5]
  [6]]]


E0000 00:00:1775882325.032873  622149 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
/home/swhors/work/mlops_jupyter_notebooks-simpson/.venv/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 10)             │           480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 5)              │            55 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 541 (2.11 KB)

 Trainable params: 541 (2.11 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 28.3027
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.7766 
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.1758 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.6490 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.1240 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.4203 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.7490 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.1449 
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.3346 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.6332 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 21.6438 
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.7400 
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 19.8414 
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 18.7681 
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 17.4233 
Epoc

In [5]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense, LSTM
from keras.callbacks import EarlyStopping

x = array([[1,2,3], [2,3,4], [3,4,5], [4,5,6], [5,6,7],
           [6,7,8], [7,8,9], [8,9,10], [9,10,11], [10,11,12],
           [20,30,40], [30,40,50], [40,50,60]])
y = array([4,5,6,7,8,9,10,11,12,13,50,60,70])

print(x.shape) # (13,3)
print(y.shape) # (13,)
x = x.reshape((x.shape[0], x.shape[1], 1))
print(x.shape) # (13,3,1)

model = Sequential()
model.add(LSTM(20, activation = 'relu', input_shape=(3,1)))
model.add(Dense(5))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mse')

early_stopping = EarlyStopping(monitor='loss', patience=100, mode='auto')
# loss값을 모니터해서 과적합이 생기면 100번 더 돌고 끊음
# mode=auto loss면 최저값이100번정도 반복되면 정지, acc면 최고값이 100번정도 반복되면 정지
# mode=min, mode=max
model.fit(x, y, epochs=1000, batch_size=1, verbose=2, callbacks=[early_stopping])

x_input = array([25,35,45]) # predict용
x_input = x_input.reshape((1,3,1))

yhat = model.predict(x_input)
print(yhat)

(13, 3)
(13,)
(13, 3, 1)
Epoch 1/1000
13/13 - 1s - 84ms/step - loss: 939.3616
Epoch 2/1000
13/13 - 0s - 5ms/step - loss: 920.8848
Epoch 3/1000
13/13 - 0s - 5ms/step - loss: 903.1669
Epoch 4/1000
13/13 - 0s - 5ms/step - loss: 883.5045
Epoch 5/1000
13/13 - 0s - 4ms/step - loss: 853.4865
Epoch 6/1000
13/13 - 0s - 4ms/step - loss: 793.5908
Epoch 7/1000
13/13 - 0s - 4ms/step - loss: 731.5232
Epoch 8/1000
13/13 - 0s - 4ms/step - loss: 590.3335
Epoch 9/1000
13/13 - 0s - 5ms/step - loss: 416.3486
Epoch 10/1000
13/13 - 0s - 4ms/step - loss: 119.1511
Epoch 11/1000
13/13 - 0s - 4ms/step - loss: 38.6759
Epoch 12/1000
13/13 - 0s - 4ms/step - loss: 29.0513
Epoch 13/1000
13/13 - 0s - 4ms/step - loss: 19.9458
Epoch 14/1000
13/13 - 0s - 4ms/step - loss: 11.6663
Epoch 15/1000
13/13 - 0s - 4ms/step - loss: 11.0624
Epoch 16/1000
13/13 - 0s - 4ms/step - loss: 4.4793
Epoch 17/1000
13/13 - 0s - 4ms/step - loss: 4.8159
Epoch 18/1000
13/13 - 0s - 4ms/step - loss: 3.9019
Epoch 19/1000
13/13 - 0s - 3ms/step - lo

In [ ]:

"""
아래 코드는 EarlyStopping이 적용되지 않습니다.
왜냐하면, EarlyStopping의 인수인 monitor의 지표는 컴파일 할때 
사용하는 loss의 지표와 같아야 합니다. 따라서 loss='acc'면
monitor='acc'로 맞춰줘야 하는 것 입니다
"""

from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping
import numpy as np
 
x_train = np.array([1,2,3,4,5,6,7,8,9,10])
y_train = np.array([1,2,3,4,5,6,7,8,9,10])
x_test = np.array([11,12,13,14,15,16,17,18,19,20])
y_test = np.array([11,12,13,14,15,16,17,18,19,20])
x_predict = np.array([21,22,23,24,25])
 
model = Sequential()
# model.add(Dense(10, input_dim=1, activation='relu'))
model.add(Dense(10, input_shape=(1, ), activation='relu'))
model.add(Dense(5))
model.add(Dense(5))
model.add(Dense(1))

# model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
# early_stopping = EarlyStopping(monitor='loss', patience=10, mode='auto')
early_stopping = EarlyStopping(monitor='loss', patience=10, mode='auto')
model.fit(x_train, y_train, epochs=1000, verbose=2, batch_size=1, callbacks=[early_stopping])

Epoch 1/100


ValueError: Could not interpret loss identifier: acc

In [ ]:
### LSTM을 DNN으로 구현한 코드

# lstm -> dnn 좋음
# dnn -> lstm 별로 dnn은 불연속적인 데이터에 많이 사용하기 때문
# cnn -> lstm -> dnn도 가능
 
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, LSTM
 
a = np.array(range(1,11))
 
size = 5
 
def split_x(seq, size):
    aaa = []
    for i in range(len(seq) - size + 1):
        subset = seq[i:(i+size)]
        aaa.append([item for item in subset])
    print(type(aaa))
    return np.array(aaa)
 
dataset = split_x(a, size)
print('------------------')
print(dataset)
 
# RESULT
# size = 5
# [[ 1  2  3  4  5]
#  [ 2  3  4  5  6]
#  [ 3  4  5  6  7]
#  [ 4  5  6  7  8]
#  [ 5  6  7  8  9]
#  [ 6  7  8  9 10]]
 
# 시계열 데이터는 y값이 없는 경우 많다.
# a로 y 만듬 
 
x_train = dataset[:, 0:-1]
y_train = dataset[:, -1] # [:, 4]
 
print(x_train.shape) # (6, 4)
print(y_train.shape) # (6, )
 
# x_train
# [[1 2 3 4]
#  [2 3 4 5]
#  [3 4 5 6]
#  [4 5 6 7]
#  [5 6 7 8]
#  [6 7 8 9]]
# y_train
# [ 5  6  7  8  9 10]
 
model = Sequential()
model.add(Dense(33, activation = 'relu', input_shape=(4,)))
model.add(Dense(5))
model.add(Dense(1))
# LSTM을 DNN으로 구현 가능
 
model.compile(optimizer='adam', loss='mse')
model.fit(x_train, y_train, epochs=100, batch_size=1, verbose=2)
 
x_input = np.array([7,8,9,10]) # (4,)
x_input = x_input.reshape(1,4)
 
yhat = model.predict(x_input)
print(yhat)

In [ ]:
### LSTM을 사용할 때 훈련 시킨 데이터의 구간 외를 예측하는 것은 오차가 많이 발생합니다.


# input_shape=(x, )  ->  실제 input(None, x)
# input_shape=(x, y) -> 실제 input(None, x, y)
 
from numpy import array
from keras.models import Sequential
from keras.layers import Dense, LSTM
from keras.callbacks import EarlyStopping

x = array([[1,2,3], [2,3,4], [3,4,5], [4,5,6], [5,6,7],
            [6,7,8], [7,8,9], [8,9,10], [9,10,11], [10,11,12],
            [20,30,40], [30,40,50], [40,50,60]])
y = array([4,5,6,7,8,9,10,11,12,13,50,60,70])

print(x.shape) # (13,3)
print(y.shape) # (13,)
x = x.reshape((x.shape[0], x.shape[1], 1))
print(x.shape) # (13,3,1)

model = Sequential()
# model.add(LSTM(20, activation = 'relu', input_shape=(3,1))) # (None, 3, 1)
# model.add(LSTM(3)) # (None, 3) -> Value error
model.add(LSTM(10, activation = 'relu', input_shape=(3,1), return_sequences=True))
model.add(LSTM(10, activation = 'relu', return_sequences=True)) # (None, 3, 10)을 받는다
model.add(LSTM(10, activation = 'relu', return_sequences=True))
model.add(LSTM(10, activation = 'relu', return_sequences=True))
model.add(LSTM(10, activation = 'relu', return_sequences=True))
model.add(LSTM(10, activation = 'relu', return_sequences=True))
model.add(LSTM(10, activation = 'relu', return_sequences=True))
model.add(LSTM(10, activation = 'relu', return_sequences=True))
model.add(LSTM(3)) # 마지막은 return_sequence X 
# return_sequence를 쓰면 dimension이 한개 추가 되므로 다음 Dense Layer의 인풋에 3 dim이 들어가게 되므로 안씀
# LSTM 두개를 엮을 때
model.add(Dense(5))
model.add(Dense(1))

model.summary()

model.compile(optimizer='adam', loss='mse')

early_stopping = EarlyStopping(monitor='loss', patience=100, mode='auto')
model.fit(x, y, epochs=1, batch_size=1, verbose=2, callbacks=[early_stopping])

x_input = array([25,35,45]) # predict용
x_input = x_input.reshape((1,3,1))

yhat = model.predict(x_input)
print(yhat)

# LSTM을 2개 이상 많이 엮으면 좋지 않다.

In [ ]:
## LSTM을 사용할 때 훈련 시킨 데이터의 구간 외를 예측하는 것은 오차가 많이 발생합니다.

from numpy import array
from keras.models import Sequential
from keras.layers import Dense, LSTM

x = array([[1,2,3], [2,3,4], [3,4,5], [4,5,6], [5,6,7],
            [6,7,8], [7,8,9], [8,9,10], [9,10,11], [10,11,12],
            [20,30,40], [30,40,50], [40,50,60]])
y = array([4,5,6,7,8,9,10,11,12,13,50,60,70])

print(x.shape) # (13,3)
print(y.shape) # (13,)
x = x.reshape((x.shape[0], x.shape[1], 1))
print(x.shape) # (13,3,1)

model = Sequential()
model.add(LSTM(200, activation = 'relu', input_shape=(3,1)))
model.add(Dense(10))
model.add(Dense(100))
model.add(Dense(10))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=200, batch_size=1)

x_input = array([25,35,45]) # predict용
x_input = x_input.reshape((1,3,1))

yhat = model.predict(x_input)
print(yhat)